### PR TITLE
Ped animations interface

### PR DESCRIPTION
**Pull request by dynamoNg**

### CODE REVIEW

**Comment by DayibBaba** [comment]
@dynamoNg Could I borrow your ped_animations.json?

**Comment by dynamoNg** [comment]
yes let me share you

**Comment by dynamoNg** [comment]
[ped_animations.zip](https://github.com/dynamoNg/YimMenu/files/12322700/ped_animations.zip)

**Comment by dynamoNg** [comment]
f801f39e (HEAD -> ped-animations-interface) add custom ptx tab
d998a0af add scenerios list

branches have been created for the respective commits and pr is closed now.

**Pull request closed without merging**
